In [2]:
# Importar o Numpy
import numpy as np

In [3]:
# Venda e Comissão
venda_valor = [150000,230000,82000,143000,184000]
comissao = [5,8,8,5,12]

In [4]:
# Qual o tipo desse dado ?
type(venda_valor)

list

In [5]:
# Ao tentar fazer uma operação com listas, teremos erro
venda_valor * (comissao/100)
# Para isso temos que transformar em um Array do NumPy

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [6]:
# Transformar lista em Array
venda_valor_array = np.array(venda_valor)
comissao_array = np.array(comissao)

In [7]:
# Com os valores transformados em Array, podemos realizar a multiplicação que nao foi possível acima
venda_valor_array * (comissao_array/100)


array([ 7500., 18400.,  6560.,  7150., 22080.])

In [8]:
# Copiando o exemplo
a = np.arange(15).reshape(3,5)
# criando um array com 15 posições, criando 3 arrays com 5 elementos cada

In [9]:
# Verificar quantidade de linhas e coluna de um array
a.shape

(3, 5)

In [10]:
# tipo dos dados
a. dtype

dtype('int32')

In [11]:
# Considerando os 3 arrays abaixo
array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4.5,5])
array3 = np.array([1,2,3,'4',5])

In [12]:
# Verificando o tipo de dado do primeiro array e retornando esse array
array1.dtype

dtype('int32')

In [13]:
# o mesmo para o 2 array
array2.dtype

dtype('float64')

In [14]:
# o mesmo para o 3 array
array3.dtype

dtype('<U11')

In [15]:
# Criando um array qualquer de numeros inteiros

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
# Criando um segundo array com valores decimais

b = np.array([1,2,3,4.7, 5])
b

array([1. , 2. , 3. , 4.7, 5. ])

In [19]:
# Criando um array apenas com valores zero

np.zeros(8).reshape(2,4)
np.ones(8).reshape(2,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# Criando um array com uma lista de valores
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
# Adicionando um intervalo para o array

np.arange(15, 26)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [24]:
# Adicionando um "Passo" para o array

np.arange(15, 26, 2)

array([15, 17, 19, 21, 23, 25])

# Criando um novo array com os valores igualmente espaçados (utilizando o linspace)

In [28]:
# Valor inicial, valor final e quantos elementos eu quero que apareça entre esses numeros
np.linspace(5,10, 20)

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [30]:
# Vamos considerar esses dados abaixo

dados_venda = np.array([[150000,230000,82000,143000,184000], [5,8,8,5,12]])

In [31]:
dados_venda.shape

(2, 5)

In [32]:
# Verificando o tipo de dados

dados_venda.dtype

dtype('int32')

In [34]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
# buscando a primeira linha
a[0]

array([0, 1, 2, 3, 4])

In [37]:
# primeira linha, elemento do índice 3
a[0][3]

3

In [39]:
# Buscando os elementos de índice 1 a 3 (incluindo o 3) na primeira linha
a[0][1:4]

array([1, 2, 3])

In [40]:
# Buscando apenas valores maiores que 5
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
novo_array = a[(a>5) & (a<11)]

In [48]:
# Visualizando o Array
novo_array

array([ 6,  7,  8,  9, 10])

In [49]:
# Considerando o array abaixo
dados = np.arange(6).reshape(2,3)
dados

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
# Somando todos os valores
dados.sum()

15

In [52]:
# Somando apenas os valores da linha

dados.sum(axis=1)

array([ 3, 12])

In [53]:
# Fazendo a soma acumulada desses valores
dados.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [54]:
# Somando apenas valores da coluna
dados.sum(axis=0)

array([3, 5, 7])

In [55]:
# Somando 1 em todos os valores
dados+1

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# Multiplicando 2 em todos os valores do array
dados*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [57]:
# Verificando o menor valor desse array
dados.min()

0

In [58]:
# Menor valor de cada linha
dados.min(axis=1)

array([0, 3])

In [59]:
# Menor valor de cada coluna
dados.min(axis=0)

array([0, 1, 2])

In [60]:
# Maior valor do array
dados.max()

5

In [61]:
# Maior valor de cada linha
dados.max(axis=1)

array([2, 5])

In [62]:
# Maior valor de cada coluna
dados.max(axis=0)

array([3, 4, 5])

In [63]:
# Calculando a média da primeira linha
dados[0].mean()

1.0

In [64]:
# Calculando a média da segunda linha
dados[1].mean()

4.0

In [65]:
# Verificando a mediana
np.median(dados)

2.5

In [69]:
# considerando 2 arrays
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

In [70]:
# Somando arrays
array1+array2

array([ 7,  9, 11, 13, 15])

In [71]:
# Multiplicando esses arrays
array1*array2

array([ 6, 14, 24, 36, 50])

In [72]:
# Potencia
array1**array2

array([      1,     128,    6561,  262144, 9765625])